 name: allure-junit5-maven

 on: [ push ]

 env:
   COUNT: Monday

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3

       - name: Set up JDK 19
         uses: actions/setup-java@v3
         with:
           java-version: '19'
           distribution: 'temurin'

       - name: Run Test
         if: always()
         run: mvn clean test
         continue-on-error: true
        
       - name: "report"
         id: report
         uses: mikepenz/action-junit-report@v3
         if: success() || failure()
         with:
           report_paths: '**/target/surefire-reports/TEST-*.xml'
          
       - name: 'print'
         run: echo REPORT "${{ github.workspace }}"
   
       - name: Send email
         uses: dawidd6/action-send-mail@v3
         if: always()
         with:
           server_address: smtp.gmail.com
           server_port: 465
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
           subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
           body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} <br> ALL TESTS COUNT IS "${{steps.report.outputs.total}}" FAILED TESTS IS "${{steps.report.outputs.failed}}" PASS TESTS IS "${{steps.report.outputs.passed}}"
           to: ${{ secrets.EMAIL_USERNAME }}
           from: John Doe
