name: Allure Report

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
         java-version: '19'
         distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean test
      continue-on-error: true
      
    - name: Generate Allure Report
      run: |
        apt-get -y install allure
        allure generate allure-results --clean -o target/allure-report

    - name: Archive Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/allure-report

    - name: Send Email with Allure Report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Allure Report'
        body: 'Please find attached the Allure report for the latest build.'
        attachments: target/allure-report.zip
